{
    "openapi": "3.0.0",
    "info": {
        "title": "RE:SPEC's APIs",
        "version": "1.0.0",
        "description": "Test the APIs!"
    },
    "host": "localhost:5000",
    "basePath": "/",
    "schemes": [
        "http"
    ],
    "components": {
        "schemas": {
            "Auth": {
                "schema01": {},
                "schema02": {}
            }
        }
    },
    "paths": {
        "/auth/register": {
            "post": {
                "summary": "유저 회원가입",
                "tags": [
                    "Auth"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "username": {
                                        "description": "유저 닉네임",
                                        "type": "string"
                                    },
                                    "email": {
                                        "description": "유저 이메일",
                                        "type": "string"
                                    },
                                    "password": {
                                        "description": "유저 비밀번호",
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "username": "RESPEC001",
                                    "email": "RESPEC001@naver.com",
                                    "password": "123"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "회원가입 성공.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "description": "관련 데이터",
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "message": "Register success.",
                                        "data": "No data."
                                    }
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "승인 거부.",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "로그인 상태에서 회원가입 시.": {
                                        "value": {
                                            "message": "You are already logged in.",
                                            "detail": "No detail."
                                        }
                                    },
                                    "이미 존재하는 유저 일시.": {
                                        "value": {
                                            "message": "Exist email or username.",
                                            "detail": "No detail."
                                        }
                                    }
                                },
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "detail": {
                                            "description": "오류에 대한 세부정보",
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "서버 DB & 서버 에러",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "detail": {
                                            "description": "오류에 대한 세부정보",
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "summary": "로컬 로그인",
                "tags": [
                    "Auth"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "email": {
                                        "description": "유저 이메일",
                                        "type": "string"
                                    },
                                    "password": {
                                        "description": "유저 비밀번호",
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "email": "RESPEC001@naver.com",
                                    "password": "123"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "로그인 성공.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "properties": {
                                                "id": {
                                                    "type": "integer"
                                                },
                                                "profile": {
                                                    "description": "프로필 사진 주소",
                                                    "type": "string"
                                                },
                                                "username": {
                                                    "description": "유저 닉네임",
                                                    "type": "string"
                                                },
                                                "email": {
                                                    "description": "유저 이메일",
                                                    "type": "string"
                                                },
                                                "password": {
                                                    "description": "유저 비밀번호",
                                                    "type": "string"
                                                },
                                                "introduction": {
                                                    "description": "유저 소개글",
                                                    "type": "string"
                                                },
                                                "phonenum": {
                                                    "description": "유저 전화번호",
                                                    "type": "string"
                                                },
                                                "position": {
                                                    "description": "멘티 OR 멘토",
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    },
                                    "example": {
                                        "message": "Local login success.",
                                        "data": {
                                            "id": "사용자 ID",
                                            "profile": "프로필 사진 주소",
                                            "username": "유저 닉네임",
                                            "email": "유저 이메일",
                                            "password": "유저 비밀번호",
                                            "introduction": "유저 소개글",
                                            "phonenum": "유저 전화번호",
                                            "position": "멘티 OR 멘토"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "승인 거부.",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "로그인 상태에서 재로그인 시.": {
                                        "value": {
                                            "message": "You are already logged in.",
                                            "detail": "No detail."
                                        }
                                    },
                                    "비밀번호가 틀릴 시.": {
                                        "value": {
                                            "message": "Invalid password.",
                                            "detail": "No detail."
                                        }
                                    }
                                },
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "detail": {
                                            "description": "오류에 대한 세부정보",
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "존재하지 않는 유저로 로그인 시.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "detail": {
                                            "description": "오류에 대한 세부정보",
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "message": "User does not exist.",
                                        "detail": "No detail."
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "서버 DB & 서버 에러",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "detail": {
                                            "description": "오류에 대한 세부정보",
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "message": "Error: Failed to serialize user into session.",
                                        "detail": "No detail."
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "get": {
                "summary": "유저 로그아웃",
                "description": "로그인 상태에서 이뤄져야 합니다.",
                "tags": [
                    "Auth"
                ],
                "responses": {
                    "200": {
                        "description": "로그아웃 성공.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "description": "관련 데이터",
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "message": "Logout success.",
                                        "data": "No data."
                                    }
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "로그아웃 상태에서 재로그아웃 시.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "detail": {
                                            "description": "오류에 대한 세부정보",
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "message": "You are not logged in.",
                                        "detail": "No detail."
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/login/kakao": {
            "get": {
                "summary": "카카오 로그인",
                "description": "OAuth를 통한 소셜 로그인이 이루어집니다.",
                "tags": [
                    "Auth"
                ],
                "responses": {
                    "200": {
                        "description": "로그인 성공.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "properties": {
                                                "id": {
                                                    "type": "integer"
                                                },
                                                "profile": {
                                                    "description": "프로필 사진 주소",
                                                    "type": "string"
                                                },
                                                "username": {
                                                    "description": "유저 닉네임",
                                                    "type": "string"
                                                },
                                                "email": {
                                                    "description": "유저 이메일",
                                                    "type": "string"
                                                },
                                                "password": {
                                                    "description": "유저 비밀번호",
                                                    "type": "string"
                                                },
                                                "introduction": {
                                                    "description": "유저 소개글",
                                                    "type": "string"
                                                },
                                                "phonenum": {
                                                    "description": "유저 전화번호",
                                                    "type": "string"
                                                },
                                                "position": {
                                                    "description": "멘티 OR 멘토",
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    },
                                    "example": {
                                        "message": "Kakao login success.",
                                        "data": {
                                            "id": "사용자 ID",
                                            "profile": "프로필 사진 주소",
                                            "username": "유저 닉네임",
                                            "email": "KAKAO유저 이메일",
                                            "password": "유저 비밀번호",
                                            "introduction": "유저 소개글",
                                            "phonenum": "유저 전화번호",
                                            "position": "멘티 OR 멘토"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "존재하지 않는 유저로 로그인 시.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "detail": {
                                            "description": "오류에 대한 세부정보",
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "message": "Kakao user not found.",
                                        "detail": "No detail."
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/login/google": {
            "get": {
                "summary": "구글 로그인",
                "description": "OAuth를 통한 소셜 로그인이 이루어집니다.",
                "tags": [
                    "Auth"
                ],
                "responses": {
                    "200": {
                        "description": "로그인 성공.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "properties": {
                                                "id": {
                                                    "type": "integer"
                                                },
                                                "profile": {
                                                    "description": "프로필 사진 주소",
                                                    "type": "string"
                                                },
                                                "username": {
                                                    "description": "유저 닉네임",
                                                    "type": "string"
                                                },
                                                "email": {
                                                    "description": "유저 이메일",
                                                    "type": "string"
                                                },
                                                "password": {
                                                    "description": "유저 비밀번호",
                                                    "type": "string"
                                                },
                                                "introduction": {
                                                    "description": "유저 소개글",
                                                    "type": "string"
                                                },
                                                "phonenum": {
                                                    "description": "유저 전화번호",
                                                    "type": "string"
                                                },
                                                "position": {
                                                    "description": "멘티 OR 멘토",
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    },
                                    "example": {
                                        "message": "Google login success.",
                                        "data": {
                                            "id": "사용자 ID",
                                            "profile": "프로필 사진 주소",
                                            "username": "유저 닉네임",
                                            "email": "GOOGLE유저 이메일",
                                            "password": "유저 비밀번호",
                                            "introduction": "유저 소개글",
                                            "phonenum": "유저 전화번호",
                                            "position": "멘티 OR 멘토"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "존재하지 않는 유저로 로그인 시.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "detail": {
                                            "description": "오류에 대한 세부정보",
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "message": "Google user not found.",
                                        "detail": "No detail."
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/login/naver": {
            "get": {
                "summary": "네이버 로그인",
                "description": "OAuth를 통한 소셜 로그인이 이루어집니다.",
                "tags": [
                    "Auth"
                ],
                "responses": {
                    "200": {
                        "description": "로그인 성공.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "properties": {
                                                "id": {
                                                    "type": "integer"
                                                },
                                                "profile": {
                                                    "description": "프로필 사진 주소",
                                                    "type": "string"
                                                },
                                                "username": {
                                                    "description": "유저 닉네임",
                                                    "type": "string"
                                                },
                                                "email": {
                                                    "description": "유저 이메일",
                                                    "type": "string"
                                                },
                                                "password": {
                                                    "description": "유저 비밀번호",
                                                    "type": "string"
                                                },
                                                "introduction": {
                                                    "description": "유저 소개글",
                                                    "type": "string"
                                                },
                                                "phonenum": {
                                                    "description": "유저 전화번호",
                                                    "type": "string"
                                                },
                                                "position": {
                                                    "description": "멘티 OR 멘토",
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    },
                                    "example": {
                                        "message": "Naver login success.",
                                        "data": {
                                            "id": "사용자 ID",
                                            "profile": "프로필 사진 주소",
                                            "username": "유저 닉네임",
                                            "email": "NAVER유저 이메일",
                                            "password": "유저 비밀번호",
                                            "introduction": "유저 소개글",
                                            "phonenum": "유저 전화번호",
                                            "position": "멘티 OR 멘토"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "존재하지 않는 유저로 로그인 시.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "detail": {
                                            "description": "오류에 대한 세부정보",
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "message": "Naver user not found.",
                                        "detail": "No detail."
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/user/register/mentor": {
            "post": {
                "summary": "멘토 등록",
                "description": "멘티인 상태인 사람만 등록할 수 있습니다.",
                "tags": [
                    "User"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "job": {
                                        "type": "string"
                                    },
                                    "company": {
                                        "type": "string"
                                    },
                                    "companysize": {
                                        "type": "string"
                                    },
                                    "career": {
                                        "type": "string"
                                    },
                                    "university": {
                                        "type": "string"
                                    },
                                    "education": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "job": "직업명",
                                    "company": "회사명",
                                    "companysize": "회사규모(대기업, 중견기업...)",
                                    "career": "경력(1~4년차, 5~8년차...)",
                                    "university": "재학 or 졸업한 대학명",
                                    "education": "학력(대학교(4년제), 석사...)"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "멘토 등록 성공.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "description": "관련 데이터",
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "message": "Mentor register success.",
                                        "data": "No data."
                                    }
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "승인 거부.",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "로그아웃 상태에서 멘토 등록 시.": {
                                        "value": {
                                            "message": "You are not logged in.",
                                            "detail": "No detail."
                                        }
                                    },
                                    "이미 멘토일 시.": {
                                        "value": {
                                            "message": "You are already mentor.",
                                            "detail": "No detail."
                                        }
                                    }
                                },
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "detail": {
                                            "description": "오류에 대한 세부정보",
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "서버 DB & 서버 에러",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "detail": {
                                            "description": "오류에 대한 세부정보",
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/menu/top/search/mentor": {
            "get": {
                "summary": "키워드를 통한 멘토 검색",
                "tags": [
                    "Menu"
                ],
                "parameters": [
                    {
                        "description": "직업명 OR 유저 키워드",
                        "name": "word",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "검색 성공.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "count": {
                                            "type": "integer"
                                        },
                                        "id": {
                                            "type": "integer"
                                        },
                                        "username": {
                                            "type": "string"
                                        },
                                        "profile": {
                                            "type": "string"
                                        },
                                        "company": {
                                            "type": "string"
                                        },
                                        "career": {
                                            "type": "string"
                                        },
                                        "characteristic": {
                                            "type": "string"
                                        },
                                        "job": {
                                            "type": "string"
                                        },
                                        "Mentorinfo": {
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "message": "Search mento data by keyword success.",
                                        "data": {
                                            "count": 1,
                                            "rows": [
                                                {
                                                    "id": 1,
                                                    "username": "RESPEC001",
                                                    "profile": null,
                                                    "Career": {
                                                        "company": "당근",
                                                        "career": "5~8년차"
                                                    },
                                                    "Characteristics": [
                                                        {
                                                            "characteristic": "논리적인"
                                                        },
                                                        {
                                                            "characteristic": "쾌활한"
                                                        }
                                                    ],
                                                    "Jobs": [
                                                        {
                                                            "job": "인프라/보안"
                                                        }
                                                    ],
                                                    "Mentorinfo": {
                                                        "introduction": "안녕하세요!"
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "존재하지 않는 데이터.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "detail": {
                                            "description": "오류에 대한 세부정보",
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "message": "No data.",
                                        "detail": "No detail."
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/menu/bottom/search/mentor": {
            "get": {
                "summary": "필터를 통한 멘토 검색",
                "tags": [
                    "Menu"
                ],
                "parameters": [
                    {
                        "description": "직업명 (입력예시 -> QA,DBA,클라우드)",
                        "name": "job",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "재학 or 졸업한 대학명",
                        "name": "university",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "학력(대학교(4년제), 석사...)",
                        "name": "education",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "회사규모(대기업, 중견기업...)",
                        "name": "companysize",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "경력(1~4년차, 5~8년차...)",
                        "name": "career",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "검색 성공.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "count": {
                                            "type": "integer"
                                        },
                                        "id": {
                                            "type": "integer"
                                        },
                                        "username": {
                                            "type": "string"
                                        },
                                        "profile": {
                                            "type": "string"
                                        },
                                        "company": {
                                            "type": "string"
                                        },
                                        "career": {
                                            "type": "string"
                                        },
                                        "characteristic": {
                                            "type": "string"
                                        },
                                        "job": {
                                            "type": "string"
                                        },
                                        "Mentorinfo": {
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "message": "Search mento data by filter success.",
                                        "data": {
                                            "count": 1,
                                            "rows": [
                                                {
                                                    "id": 1,
                                                    "username": "RESPEC001",
                                                    "profile": null,
                                                    "Career": {
                                                        "company": "당근",
                                                        "career": "5~8년차"
                                                    },
                                                    "Characteristics": [
                                                        {
                                                            "characteristic": "논리적인"
                                                        },
                                                        {
                                                            "characteristic": "쾌활한"
                                                        }
                                                    ],
                                                    "Jobs": [
                                                        {
                                                            "job": "인프라/보안"
                                                        }
                                                    ],
                                                    "Mentorinfo": {
                                                        "introduction": "안녕하세요!"
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "존재하지 않는 데이터.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        },
                                        "detail": {
                                            "description": "오류에 대한 세부정보",
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "message": "No data.",
                                        "detail": "No detail."
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}